import { useEffect, useState } from 'react'
import { Copy, CreditCard, ExternalLink, RefreshCw, ShoppingCart, ThumbsUp, Trash2 } from 'lucide-react'
import { deleteSalesPage, getSalesPages, type SalesPage } from '../api'

function useServerBase() {
  return window.location.protocol + '//' + window.location.hostname + ':8000'
}

export default function SalesPagesPanel() {
  const base = useServerBase()
  const [pages, setPages]     = useState<SalesPage[]>([])
  const [loading, setLoading] = useState(true)
  const [copied, setCopied]   = useState<string | null>(null)
  const [deleting, setDeleting] = useState<string | null>(null)

  const load = async () => {
    setLoading(true)
    try {
      setPages(await getSalesPages())
    } catch {
      setPages([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [])

  const copyLink = (url: string, key: string) => {
    navigator.clipboard.writeText(base + url).then(() => {
      setCopied(key)
      setTimeout(() => setCopied(null), 2000)
    })
  }

  const handleDelete = async (folder: string) => {
    if (!window.confirm('Delete this sales page and all its files? This cannot be undone.')) return
    setDeleting(folder)
    try {
      await deleteSalesPage(folder)
      setPages(prev => prev.filter(p => p.folder !== folder))
    } catch {
      // ignore
    } finally {
      setDeleting(null)
    }
  }

  const labelStyle: React.CSSProperties = {
    fontSize: 11, fontWeight: 700, letterSpacing: '.06em',
    textTransform: 'uppercase', color: 'var(--muted)', marginBottom: 6, display: 'block',
  }

  return (
    <div style={{ padding: '28px 24px', maxWidth: 960, margin: '0 auto' }}>

      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 28 }}>
        <div>
          <h2 style={{ margin: 0, fontSize: 20, fontWeight: 800, color: 'var(--text)', display: 'flex', alignItems: 'center', gap: 10 }}>
            <ShoppingCart size={20} color="#58a6ff" />
            Sales Pages
          </h2>
          <p style={{ margin: '4px 0 0', fontSize: 13, color: 'var(--muted)' }}>
            Direct-sales pages with Stripe checkout — generated by the Funnel Agent
          </p>
        </div>
        <button onClick={load} style={btnStyle}>
          <RefreshCw size={13} />
          Refresh
        </button>
      </div>

      {/* Loading */}
      {loading && (
        <div style={{ textAlign: 'center', padding: 64, color: 'var(--muted)' }}>Loading sales pages...</div>
      )}

      {/* Empty state */}
      {!loading && pages.length === 0 && (
        <div style={{
          background: 'var(--surface)', border: '1px solid var(--border)',
          borderRadius: 12, padding: '64px 32px', textAlign: 'center',
        }}>
          <CreditCard size={40} color="var(--muted)" style={{ marginBottom: 16 }} />
          <h3 style={{ margin: '0 0 8px', fontSize: 16, color: 'var(--text)' }}>No sales pages yet</h3>
          <p style={{ margin: 0, color: 'var(--muted)', fontSize: 14 }}>
            Submit a <strong>sales_page_gen</strong> task in the Mega Pipeline to generate your first sales page.
          </p>
        </div>
      )}

      {/* Pages list */}
      {!loading && pages.map(page => (
        <div key={page.folder} style={{
          background: 'var(--surface)', border: '1px solid var(--border)',
          borderRadius: 12, padding: 24, marginBottom: 16,
        }}>
          {/* Title row */}
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 20 }}>
            <div>
              <h3 style={{ margin: '0 0 4px', fontSize: 16, fontWeight: 700, color: 'var(--text)', lineHeight: 1.3 }}>
                {page.title}
              </h3>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap', marginTop: 4 }}>
                <span style={{ fontSize: 12, color: 'var(--muted)' }}>
                  Created {new Date(page.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                </span>
                {page.price_point && (
                  <span style={{
                    fontSize: 12, fontWeight: 800,
                    background: 'rgba(63,185,80,.12)', color: '#3fb950',
                    border: '1px solid rgba(63,185,80,.25)', borderRadius: 4, padding: '2px 8px',
                  }}>
                    {page.price_point}
                  </span>
                )}
                {page.stripe_url && page.stripe_url !== '#' && (
                  <span style={{
                    fontSize: 11, fontWeight: 700,
                    background: 'rgba(88,166,255,.12)', color: '#58a6ff',
                    border: '1px solid rgba(88,166,255,.25)', borderRadius: 4, padding: '2px 8px',
                    display: 'flex', alignItems: 'center', gap: 4,
                  }}>
                    <CreditCard size={10} /> Stripe connected
                  </span>
                )}
              </div>
            </div>
            <button
              onClick={() => handleDelete(page.folder)}
              disabled={deleting === page.folder}
              style={{ ...btnStyle, border: '1px solid rgba(248,81,73,.3)', color: deleting === page.folder ? 'var(--muted)' : '#f85149', background: 'rgba(248,81,73,.06)' }}
            >
              <Trash2 size={13} />
              {deleting === page.folder ? 'Deleting…' : 'Delete'}
            </button>
          </div>

          {/* Sales page URL */}
          <div style={{ marginBottom: 14 }}>
            <label style={labelStyle}>Sales Page</label>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
              <div style={{
                flex: 1, background: 'var(--bg)', border: '1px solid var(--border)',
                borderRadius: 8, padding: '10px 14px', fontSize: 13,
                color: 'var(--muted)', fontFamily: 'monospace', overflow: 'hidden',
                whiteSpace: 'nowrap', textOverflow: 'ellipsis',
              }}>
                {base}{page.sales_url}
              </div>
              <button onClick={() => window.open(base + page.sales_url, '_blank')} style={btnStyle}>
                <ExternalLink size={14} /> Preview
              </button>
              <button
                onClick={() => copyLink(page.sales_url, page.slug + '-sales')}
                style={{ ...btnStyle, background: copied === page.slug + '-sales' ? 'rgba(63,185,80,.15)' : undefined, color: copied === page.slug + '-sales' ? '#3fb950' : undefined }}
              >
                {copied === page.slug + '-sales' ? <ThumbsUp size={14} /> : <Copy size={14} />}
                {copied === page.slug + '-sales' ? 'Copied!' : 'Copy Link'}
              </button>
            </div>
          </div>

          {/* Thank-you page URL */}
          {page.has_thankyou && (
            <div>
              <label style={labelStyle}>Thank-You Page (post-purchase)</label>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <div style={{
                  flex: 1, background: 'var(--bg)', border: '1px solid var(--border)',
                  borderRadius: 8, padding: '10px 14px', fontSize: 13,
                  color: 'var(--muted)', fontFamily: 'monospace', overflow: 'hidden',
                  whiteSpace: 'nowrap', textOverflow: 'ellipsis',
                }}>
                  {base}{page.thankyou_url}
                </div>
                <button onClick={() => window.open(base + page.thankyou_url, '_blank')} style={btnStyle}>
                  <ExternalLink size={14} /> Preview
                </button>
                <button
                  onClick={() => copyLink(page.thankyou_url, page.slug + '-sty')}
                  style={{ ...btnStyle, background: copied === page.slug + '-sty' ? 'rgba(63,185,80,.15)' : undefined, color: copied === page.slug + '-sty' ? '#3fb950' : undefined }}
                >
                  {copied === page.slug + '-sty' ? <ThumbsUp size={14} /> : <Copy size={14} />}
                  {copied === page.slug + '-sty' ? 'Copied!' : 'Copy Link'}
                </button>
              </div>
            </div>
          )}
        </div>
      ))}
    </div>
  )
}

const btnStyle: React.CSSProperties = {
  display: 'flex', alignItems: 'center', gap: 6,
  padding: '9px 14px', borderRadius: 8,
  border: '1px solid var(--border)', background: 'var(--surface2)',
  color: 'var(--text)', cursor: 'pointer', fontSize: 13, fontWeight: 600,
  whiteSpace: 'nowrap',
}
