/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123477-g5640bd3a4f-20260314"
#endif /* AVUTIL_FFVERSION_H */
